### ISSUE TITLE
ERROR WHEN I TRY TO RUN VOLUME BOOSTER MODULE

### ISSUE THREAD

**Issue by TheNightSec** [outsmartchad/solana-memecoin-cli#12]
`root@Abdullah-PC:~/solana-memecoin-cli/src/Trading/volume# node boost_volume --token_address 3jrfnF2wttLwmDVfbtuvMXxVKoJMg6msYfaE9EZzVBq3 --cluster mainnet --sol_per_order 0.01
/root/solana-memecoin-cli/node_modules/base-x/src/index.js:113
    throw new Error('Non-base' + BASE + ' character')
    ^

Error: Non-base58 character
    at Object.decode (/root/solana-memecoin-cli/node_modules/base-x/src/index.js:113:11)
    at Object.<anonymous> (/root/solana-memecoin-cli/src/helpers/config.js:28:43)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/root/solana-memecoin-cli/src/Trading/volume/boost_volume.js:1:32)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)`

**Comment by TheNightSec** [comment]
![image](https://github.com/user-attachments/assets/1940883d-b3a4-48a9-895d-b2bf94c2c69c)

**Comment by TheNightSec** [comment]
**nevermind - fixed**
