### ISSUE TITLE
Copy trading issue with endpoint

### ISSUE THREAD

**Issue by MBSL73** [outsmartchad/solana-memecoin-cli#8]
Hi, I am trying to run the copytrading module and I am getting this error even though i have entered the endpoint correctly in the .env file:
throw new TypeError('Endpoint URL must start with `http:` or `https:`.');
at assertEndpointUrl (/home/mayo_boy/solana-memecoin-cli/node_modules/@solana/web3.js/lib/index.cjs.js:4456:11)
    at new Connection (/home/mayo_boy/solana-memecoin-cli/node_modules/@solana/web3.js/lib/index.cjs.js:6044:25)
    at Object.<anonymous> (/home/mayo_boy/solana-memecoin-cli/src/helpers/config.js:50:24)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/home/mayo_boy/solana-memecoin-cli/src/Trading/memecoin_trading_strategies/copy_trading/copy-sell.js:9:61)

any idea how to solve this?

**Comment by outsmartchad** [comment]
What rpc u are using

**Comment by outsmartchad** [comment]
yes, in https://github.com/outsmartchad/solana-memecoin-cli/blob/main/src/helpers/config.js , 1. you should copy your own .env path to change the original path, it's likely your c:// path's format is not correct, and 2. for the copy-trade, you should copy your own copy-buy & copy-sell path, and 3. change the bought_token.json path to ur own path in copy-buy and copy-sell, the way i change it is i put the path in a constant.js at the same dir, and every file refer to it and use it

**Comment by outsmartchad** [comment]
Sorry for make it complicated to get start, i will put it into a constant.js and refer to it

**Comment by MBSL73** [comment]
No problem at all, but I think I have changed all of those correctly and it's not working.

**Comment by outsmartchad** [comment]
Updated link

**Comment by Othmantork** [comment]
I'm also facing the same problem. I changed all the paths and it still says npm error could not determine executable to run

**Comment by outsmartchad** [comment]
join the dc, talk about it
